# Generated by Django 5.1.5 on 2025-01-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('admission', models.DateTimeField(verbose_name='Data de admissão')),
                ('wage', models.FloatField(default=4000, verbose_name='Salário')),
            ],
            options={
                'verbose_name': 'Doutor',
                'verbose_name_plural': 'Doutores',
                'ordering': ['name'],
            },
        ),
    ]
